name: Add a new sound
description: Adds your sounds to the Click Sounds repository
labels: []
body: 
  - type: markdown
    attributes:
      value: "## Click Sounds Request"
  - type: input
    id: name
    attributes:
      label: Click Sound Name
      description: put your click sound name here
      placeholder: Click Sound Name
    validations:
      required: true
  - type: textarea
    id: zip
    attributes:
      label: Add Pack
      description: Add your click sound files here in a **COMPRESSED *ZIP* FILE**, NOTHING ELSE
      placeholder: Input files here
    validations:
      required: true